
export const areaCode = [
  {
  "nationCode": "+86",
  "nationName": "中国"
}, {
  "nationCode": "+852",
  "nationName": "中国香港"
}, {
  "nationCode": "+853",
  "nationName": "中国澳门"
}, {
  "nationCode": "+886",
  "nationName": "中国台湾"
}, {
  "nationCode": "+1",
  "nationName": "美国"
}, {
  "nationCode": "+81",
  "nationName": "日本"
}, {
  "nationCode": "+60",
  "nationName": "马来西亚"
}, {
  "nationCode": "+61",
  "nationName": "澳大利亚"
}, {
  "nationCode": "+1",
  "nationName": "加拿大"
}, {
  "nationCode": "+44",
  "nationName": "英国"
}, {
  "nationCode": "+65",
  "nationName": "新加坡"
}, {
  "nationCode": "+49",
  "nationName": "德国"
}, {
  "nationCode": "+7",
  "nationName": "俄罗斯"
}, {
  "nationCode": "+20",
  "nationName": "埃及"
}, {
  "nationCode": "+27",
  "nationName": "南非"
}, {
  "nationCode": "+30",
  "nationName": "希腊"
}, {
  "nationCode": "+31",
  "nationName": "荷兰"
}, {
  "nationCode": "+32",
  "nationName": "比利时"
}, {
  "nationCode": "+33",
  "nationName": "法国"
}, {
  "nationCode": "+34",
  "nationName": "西班牙"
}, {
  "nationCode": "+36",
  "nationName": "匈牙利"
}, {
  "nationCode": "+39",
  "nationName": "意大利"
}, {
  "nationCode": "+40",
  "nationName": "罗马尼亚"
}, {
  "nationCode": "+41",
  "nationName": "瑞士"
}, {
  "nationCode": "+43",
  "nationName": "奥地利"
}, {
  "nationCode": "+45",
  "nationName": "丹麦"
}, {
  "nationCode": "+46",
  "nationName": "瑞典"
}, {
  "nationCode": "+47",
  "nationName": "挪威"
}, {
  "nationCode": "+47",
  "nationName": "斯瓦尔巴岛和扬马延岛"
}, {
  "nationCode": "+48",
  "nationName": "波兰"
}, {
  "nationCode": "+51",
  "nationName": "秘鲁"
}, {
  "nationCode": "+52",
  "nationName": "墨西哥"
}, {
  "nationCode": "+53",
  "nationName": "古巴"
}, {
  "nationCode": "+54",
  "nationName": "阿根廷"
}, {
  "nationCode": "+55",
  "nationName": "巴西"
}, {
  "nationCode": "+56",
  "nationName": "智利"
}, {
  "nationCode": "+57",
  "nationName": "哥伦比亚"
}, {
  "nationCode": "+58",
  "nationName": "委内瑞拉"
}, {
  "nationCode": "+61",
  "nationName": "圣诞岛"
}, {
  "nationCode": "+61",
  "nationName": "科科斯（基林）群岛"
}, {
  "nationCode": "+62",
  "nationName": "印度尼西亚"
}, {
  "nationCode": "+63",
  "nationName": "菲律宾"
}, {
  "nationCode": "+64",
  "nationName": "新西兰"
}, {
  "nationCode": "+66",
  "nationName": "泰国"
}, {
  "nationCode": "+73",
  "nationName": "哈萨克斯坦"
}, {
  "nationCode": "+82",
  "nationName": "韩国"
}, {
  "nationCode": "+84",
  "nationName": "越南"
}, {
  "nationCode": "+90",
  "nationName": "土耳其"
}, {
  "nationCode": "+91",
  "nationName": "印度"
}, {
  "nationCode": "+92",
  "nationName": "巴基斯坦"
}, {
  "nationCode": "+93",
  "nationName": "阿富汗"
}, {
  "nationCode": "+94",
  "nationName": "斯里兰卡"
}, {
  "nationCode": "+95",
  "nationName": "缅甸"
}, {
  "nationCode": "+98",
  "nationName": "伊朗"
}, {
  "nationCode": "+212",
  "nationName": "摩洛哥"
}, {
  "nationCode": "+213",
  "nationName": "阿尔及利亚"
}, {
  "nationCode": "+216",
  "nationName": "突尼斯"
}, {
  "nationCode": "+218",
  "nationName": "利比亚"
}, {
  "nationCode": "+220",
  "nationName": "冈比亚"
}, {
  "nationCode": "+221",
  "nationName": "塞内加尔"
}, {
  "nationCode": "+222",
  "nationName": "毛里塔尼亚"
}, {
  "nationCode": "+223",
  "nationName": "马里"
}, {
  "nationCode": "+224",
  "nationName": "几内亚"
}, {
  "nationCode": "+225",
  "nationName": "科特迪瓦"
}, {
  "nationCode": "+226",
  "nationName": "布基纳法索"
}, {
  "nationCode": "+227",
  "nationName": "尼日尔"
}, {
  "nationCode": "+228",
  "nationName": "多哥"
}, {
  "nationCode": "+229",
  "nationName": "贝宁"
}, {
  "nationCode": "+230",
  "nationName": "毛里求斯"
}, {
  "nationCode": "+231",
  "nationName": "利比里亚"
}, {
  "nationCode": "+232",
  "nationName": "塞拉利"
}, {
  "nationCode": "+233",
  "nationName": "加纳"
}, {
  "nationCode": "+234",
  "nationName": "尼日利亚"
}, {
  "nationCode": "+235",
  "nationName": "乍得"
}, {
  "nationCode": "+236",
  "nationName": "中非"
}, {
  "nationCode": "+237",
  "nationName": "喀麦隆"
}, {
  "nationCode": "+238",
  "nationName": "佛得角"
}, {
  "nationCode": "+239",
  "nationName": "圣多美和普林西比"
}, {
  "nationCode": "+240",
  "nationName": "赤道几内亚"
}, {
  "nationCode": "+241",
  "nationName": "加蓬"
}, {
  "nationCode": "+242",
  "nationName": "刚果（布）"
}, {
  "nationCode": "+243",
  "nationName": "刚果（金）"
}, {
  "nationCode": "+244",
  "nationName": "安哥拉"
}, {
  "nationCode": "+245",
  "nationName": "几内亚比绍"
}, {
  "nationCode": "+248",
  "nationName": "塞舌尔"
}, {
  "nationCode": "+249",
  "nationName": "苏丹"
}, {
  "nationCode": "+250",
  "nationName": "卢旺达"
}, {
  "nationCode": "+251",
  "nationName": "埃塞俄比亚"
}, {
  "nationCode": "+252",
  "nationName": "索马里"
}, {
  "nationCode": "+253",
  "nationName": "吉布提"
}, {
  "nationCode": "+254",
  "nationName": "肯尼亚"
}, {
  "nationCode": "+255",
  "nationName": "坦桑尼亚"
}, {
  "nationCode": "+256",
  "nationName": "乌干达"
}, {
  "nationCode": "+257",
  "nationName": "布隆迪"
}, {
  "nationCode": "+258",
  "nationName": "莫桑比克"
}, {
  "nationCode": "+260",
  "nationName": "赞比亚"
}, {
  "nationCode": "+261",
  "nationName": "马达加斯加"
}, {
  "nationCode": "+262",
  "nationName": "留尼汪"
}, {
  "nationCode": "+263",
  "nationName": "津巴布韦"
}, {
  "nationCode": "+264",
  "nationName": "纳米尼亚"
}, {
  "nationCode": "+265",
  "nationName": "马拉维"
}, {
  "nationCode": "+266",
  "nationName": "莱索托"
}, {
  "nationCode": "+267",
  "nationName": "博茨瓦纳"
}, {
  "nationCode": "+268",
  "nationName": "斯威士兰"
}, {
  "nationCode": "+269",
  "nationName": "科摩罗"
}, {
  "nationCode": "+269",
  "nationName": "马约特"
}, {
  "nationCode": "+290",
  "nationName": "圣赫勒拿"
}, {
  "nationCode": "+291",
  "nationName": "厄立特里亚"
}, {
  "nationCode": "+297",
  "nationName": "阿鲁巴"
}, {
  "nationCode": "+298",
  "nationName": "法罗群岛"
}, {
  "nationCode": "+299",
  "nationName": "格陵兰"
}, {
  "nationCode": "+350",
  "nationName": "直布罗陀"
}, {
  "nationCode": "+351",
  "nationName": "葡萄牙"
}, {
  "nationCode": "+352",
  "nationName": "卢森堡"
}, {
  "nationCode": "+353",
  "nationName": "爱尔兰"
}, {
  "nationCode": "+354",
  "nationName": "冰岛"
}, {
  "nationCode": "+355",
  "nationName": "阿尔巴尼亚"
}, {
  "nationCode": "+356",
  "nationName": "马耳他"
}, {
  "nationCode": "+357",
  "nationName": "塞浦路斯"
}, {
  "nationCode": "+358",
  "nationName": "芬兰"
}, {
  "nationCode": "+359",
  "nationName": "保加利亚"
}, {
  "nationCode": "+370",
  "nationName": "立陶宛"
}, {
  "nationCode": "+371",
  "nationName": "拉脱维亚"
}, {
  "nationCode": "+372",
  "nationName": "爱沙尼亚"
}, {
  "nationCode": "+373",
  "nationName": "摩尔多瓦"
}, {
  "nationCode": "+374",
  "nationName": "亚美尼亚"
}, {
  "nationCode": "+375",
  "nationName": "白俄罗斯"
}, {
  "nationCode": "+376",
  "nationName": "安道尔"
}, {
  "nationCode": "+377",
  "nationName": "摩纳哥"
}, {
  "nationCode": "+378",
  "nationName": "圣马力诺"
}, {
  "nationCode": "+379",
  "nationName": "梵蒂冈"
}, {
  "nationCode": "+380",
  "nationName": "乌克兰"
}, {
  "nationCode": "+381",
  "nationName": "塞尔维亚和黑山"
}, {
  "nationCode": "+385",
  "nationName": "克罗地亚"
}, {
  "nationCode": "+386",
  "nationName": "斯洛文尼亚"
}, {
  "nationCode": "+387",
  "nationName": "波黑"
}, {
  "nationCode": "+389",
  "nationName": "前南马其顿"
}, {
  "nationCode": "+420",
  "nationName": "捷克"
}, {
  "nationCode": "+421",
  "nationName": "斯洛伐克"
}, {
  "nationCode": "+423",
  "nationName": "列支敦士登"
}, {
  "nationCode": "+500",
  "nationName": "福克兰群岛（马尔维纳斯）"
}, {
  "nationCode": "+501",
  "nationName": "伯利兹"
}, {
  "nationCode": "+502",
  "nationName": "危地马拉"
}, {
  "nationCode": "+503",
  "nationName": "萨尔瓦多"
}, {
  "nationCode": "+504",
  "nationName": "洪都拉斯"
}, {
  "nationCode": "+505",
  "nationName": "尼加拉瓜"
}, {
  "nationCode": "+506",
  "nationName": "哥斯达黎加"
}, {
  "nationCode": "+507",
  "nationName": "巴拿马"
}, {
  "nationCode": "+508",
  "nationName": "圣皮埃尔和密克隆"
}, {
  "nationCode": "+509",
  "nationName": "海地"
}, {
  "nationCode": "+590",
  "nationName": "瓜德罗普"
}, {
  "nationCode": "+591",
  "nationName": "玻利维亚"
}, {
  "nationCode": "+592",
  "nationName": "圭亚那"
}, {
  "nationCode": "+593",
  "nationName": "厄瓜多尔"
}, {
  "nationCode": "+594",
  "nationName": "法属圭亚那"
}, {
  "nationCode": "+595",
  "nationName": "巴拉圭"
}, {
  "nationCode": "+596",
  "nationName": "马提尼克"
}, {
  "nationCode": "+597",
  "nationName": "苏里南"
}, {
  "nationCode": "+598",
  "nationName": "乌拉圭"
}, {
  "nationCode": "+599",
  "nationName": "荷属安的列斯"
}, {
  "nationCode": "+672",
  "nationName": "南极洲"
}, {
  "nationCode": "+673",
  "nationName": "文莱"
}, {
  "nationCode": "+674",
  "nationName": "瑙鲁"
}, {
  "nationCode": "+675",
  "nationName": "巴布亚新几内亚"
}, {
  "nationCode": "+676",
  "nationName": "汤加"
}, {
  "nationCode": "+677",
  "nationName": "所罗门群岛"
}, {
  "nationCode": "+678",
  "nationName": "瓦努阿图"
}, {
  "nationCode": "+679",
  "nationName": "斐济"
}, {
  "nationCode": "+680",
  "nationName": "帕劳"
}, {
  "nationCode": "+681",
  "nationName": "瓦利斯和富图纳"
}, {
  "nationCode": "+682",
  "nationName": "库克群岛"
}, {
  "nationCode": "+683",
  "nationName": "纽埃"
}, {
  "nationCode": "+684",
  "nationName": "美属萨摩亚"
}, {
  "nationCode": "+685",
  "nationName": "萨摩亚"
}, {
  "nationCode": "+686",
  "nationName": "基里巴斯"
}, {
  "nationCode": "+687",
  "nationName": "新喀里多尼亚"
}, {
  "nationCode": "+688",
  "nationName": "图瓦卢"
}, {
  "nationCode": "+689",
  "nationName": "法属波利尼西亚"
}, {
  "nationCode": "+690",
  "nationName": "托克劳"
}, {
  "nationCode": "+691",
  "nationName": "密克罗尼西亚"
}, {
  "nationCode": "+692",
  "nationName": "马绍尔群岛"
}, {
  "nationCode": "+850",
  "nationName": "朝鲜"
}, {
  "nationCode": "+855",
  "nationName": "柬埔寨"
}, {
  "nationCode": "+856",
  "nationName": "老挝"
}, {
  "nationCode": "+880",
  "nationName": "孟加拉国"
}, {
  "nationCode": "+960",
  "nationName": "马尔代夫"
}, {
  "nationCode": "+961",
  "nationName": "黎巴嫩"
}, {
  "nationCode": "+962",
  "nationName": "约旦"
}, {
  "nationCode": "+963",
  "nationName": "叙利亚"
}, {
  "nationCode": "+964",
  "nationName": "伊拉克"
}, {
  "nationCode": "+965",
  "nationName": "科威特"
}, {
  "nationCode": "+966",
  "nationName": "沙特阿拉伯"
}, {
  "nationCode": "+967",
  "nationName": "也门"
}, {
  "nationCode": "+968",
  "nationName": "阿曼"
}, {
  "nationCode": "+971",
  "nationName": "阿拉伯联合酋长国"
}, {
  "nationCode": "+972",
  "nationName": "以色列"
}, {
  "nationCode": "+973",
  "nationName": "巴林"
}, {
  "nationCode": "+974",
  "nationName": "卡塔尔"
}, {
  "nationCode": "+975",
  "nationName": "不丹"
}, {
  "nationCode": "+976",
  "nationName": "蒙古"
}, {
  "nationCode": "+977",
  "nationName": "尼泊尔"
}, {
  "nationCode": "+992",
  "nationName": "塔吉克斯坦"
}, {
  "nationCode": "+993",
  "nationName": "土库曼斯坦"
}, {
  "nationCode": "+994",
  "nationName": "阿塞拜疆"
}, {
  "nationCode": "+995",
  "nationName": "格鲁吉亚"
}, {
  "nationCode": "+996",
  "nationName": "吉尔吉斯斯坦"
}, {
  "nationCode": "+998",
  "nationName": "乌兹别克斯坦"
}, {
  "nationCode": "+1242",
  "nationName": "巴哈马"
}, {
  "nationCode": "+1246",
  "nationName": "巴巴多斯"
}, {
  "nationCode": "+1264",
  "nationName": "安圭拉"
}, {
  "nationCode": "+1268",
  "nationName": "安提瓜和巴布达"
}, {
  "nationCode": "+1284",
  "nationName": "英属维尔京群岛"
}, {
  "nationCode": "+1340",
  "nationName": "美属维尔京群岛"
}, {
  "nationCode": "+1345",
  "nationName": "开曼群岛"
}, {
  "nationCode": "+1441",
  "nationName": "百慕大"
}, {
  "nationCode": "+1473",
  "nationName": "格林纳达"
}, {
  "nationCode": "+1481",
  "nationName": "根西岛"
}, {
  "nationCode": "+1649",
  "nationName": "特克斯和凯科斯群岛"
}, {
  "nationCode": "+1664",
  "nationName": "蒙特塞拉特"
}, {
  "nationCode": "+1671",
  "nationName": "关岛"
}, {
  "nationCode": "+1758",
  "nationName": "圣卢西亚"
}, {
  "nationCode": "+1767",
  "nationName": "多米尼克"
}, {
  "nationCode": "+1784",
  "nationName": "圣文森特和格林纳丁斯"
}, {
  "nationCode": "+1809",
  "nationName": "多米尼加"
}, {
  "nationCode": "+1809",
  "nationName": "波多黎各"
}, {
  "nationCode": "+1868",
  "nationName": "特立尼达和多巴哥"
}, {
  "nationCode": "+1869",
  "nationName": "圣基茨和尼维斯"
}, {
  "nationCode": "+1876",
  "nationName": "牙买加"
}, {
  "nationCode": "+6723",
  "nationName": "诺福克岛"
}];
